//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GRomash.CrmWebApiEarlyBoundGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GRomash.CrmWebApiEarlyBoundGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Dynamic;
        ///using System.CodeDom.Compiler;
        ///using System.Diagnostics.CodeAnalysis;
        ///
        ///namespace {Namespace}
        ///{
        ///	[ExcludeFromCodeCoverage]
        ///	[GeneratedCode(&quot;CrmWebApiEarlyBoundGenerator&quot;, &quot;1.0.4.0&quot;)]
        ///    public class {EntityName} : Entity
        ///    {
        ///		public new const string EntityLogicalName = &quot;{EntityLogicalName}&quot;;
        ///		
        ///		public new const string EntitySetName = &quot;{EntitySetName}&quot;;
        ///
        ///        public const string PrimaryIdAttribute = &quot;{PrimaryIdAttribute}&quot;;
        ///
        ///		public {EntityName}(Ex [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClassTemplate {
            get {
                return ResourceManager.GetString("ClassTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         [OnlyDate].
        /// </summary>
        internal static string DateOnlyAttributeTemplate {
            get {
                return ResourceManager.GetString("DateOnlyAttributeTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Linq;
        ///using System.Dynamic;
        ///using System.Reflection;
        ///using System.CodeDom.Compiler;
        ///using System.Collections.Generic;
        ///using System.Diagnostics.CodeAnalysis;
        ///
        ///namespace {Namespace}
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Base class for entities for work with web api
        ///    /// &lt;/summary&gt;
        ///    [ExcludeFromCodeCoverage]
        ///	[GeneratedCode(&quot;CrmWebApiEarlyBoundGenerator&quot;, &quot;1.0.4.0&quot;)]
        ///    public class Entity
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// For store entity attributes
        ///        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Entity {
            get {
                return ResourceManager.GetString("Entity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         [EntityAttribute(&quot;{EntityLogicalName}&quot;, &quot;{AttributeName}&quot;)].
        /// </summary>
        internal static string EntityAttributeTemplate {
            get {
                return ResourceManager.GetString("EntityAttributeTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         [EntityReferenceAttribute(&quot;{EntitySetName}&quot;, &quot;{ValueField}&quot;)].
        /// </summary>
        internal static string EntityReferenceAttributeTemplate {
            get {
                return ResourceManager.GetString("EntityReferenceAttributeTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to             public const string {FieldName} = &quot;{AttributeName}&quot;;.
        /// </summary>
        internal static string FieldConstTemplate {
            get {
                return ResourceManager.GetString("FieldConstTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		/// &lt;summary&gt;
        ///        /// {Description}
        ///        /// &lt;/summary&gt;
        ///{Attributes}
        ///        public {Type} {PropertyName} {
        ///            get =&gt; GetAttributeValue&lt;{Type}&gt;({AttributeName});
        ///            set =&gt; SetAttributeValue({AttributeName}, value);
        ///        }
        ///.
        /// </summary>
        internal static string PropertyTemplate {
            get {
                return ResourceManager.GetString("PropertyTemplate", resourceCulture);
            }
        }
    }
}
